class_name RuntimeActionParamManifest
extends RefCounted

# Direct data translation of src/core/actionParamManifest.ts.
const ACTION_PARAM_MANIFEST := {
	"setFlag": {"required": ["key", "value"], "nonEmpty": ["key"]},
	"appendFlag": {"required": ["key", "text"], "nonEmpty": ["key"]},
	"addFlagValue": {"required": ["key", "delta"], "nonEmpty": ["key"]},
	"showNotification": {"required": ["text"], "optional": ["type"]},
	"runActions": {"required": ["actions"]},
	"chooseAction": {"required": ["options"], "optional": ["prompt", "allowCancel"]},
	"randomBranch": {"required": [], "optional": ["probability", "aboveActions", "belowActions"]},
	"emitNarrativeSignal": {"required": ["signal"], "nonEmpty": ["signal"], "optional": ["sourceType", "sourceId"]},
	"setScenarioPhase": {"required": ["scenarioId", "phase", "status"], "nonEmpty": ["scenarioId", "phase", "status"], "optional": ["outcome"]},
	"startScenario": {"required": ["scenarioId"], "nonEmpty": ["scenarioId"]},
	"activateScenario": {"required": ["scenarioId"], "nonEmpty": ["scenarioId"]},
	"completeScenario": {"required": ["scenarioId"], "nonEmpty": ["scenarioId"]},
	"revealDocument": {"required": ["documentId"], "nonEmpty": ["documentId"]},
	"giveItem": {"required": ["id"], "nonEmpty": ["id"], "optional": ["count", "critical"]},
	"removeItem": {"required": ["id"], "nonEmpty": ["id"], "optional": ["count"]},
	"giveCurrency": {"required": ["amount"]},
	"removeCurrency": {"required": ["amount"], "nonEmpty": ["amount"]},
	"giveRule": {"required": ["id"], "nonEmpty": ["id"]},
	"grantRuleLayer": {"required": ["ruleId", "layer"], "nonEmpty": ["ruleId", "layer"]},
	"giveFragment": {"required": ["id"], "nonEmpty": ["id"]},
	"updateQuest": {"required": ["id"], "nonEmpty": ["id"]},
	"pickup": {"required": ["itemName", "count"], "nonEmpty": ["itemName"], "optional": ["itemId", "isCurrency"]},
	"shopPurchase": {"required": ["itemId", "price"], "nonEmpty": ["itemId"]},
	"inventoryDiscard": {"required": ["itemId"], "nonEmpty": ["itemId"]},
	"openShop": {"required": ["shopId"], "nonEmpty": ["shopId"]},
	"startEncounter": {"required": ["id"], "nonEmpty": ["id"]},
	"playBgm": {"required": ["id"], "nonEmpty": ["id"], "optional": ["fadeMs"]},
	"stopBgm": {"required": [], "optional": ["fadeMs"]},
	"playSfx": {"required": ["id"], "nonEmpty": ["id"], "optional": ["volume"]},
	"stopSceneAmbient": {"required": [], "optional": ["id", "fadeMs"]},
	"endDay": {"required": []},
	"addDelayedEvent": {"required": ["targetDay", "actions"]},
	"addArchiveEntry": {"required": ["bookType", "entryId"], "nonEmpty": ["bookType", "entryId"]},
	"startCutscene": {"required": ["id"], "nonEmpty": ["id"]},
	"startWaterMinigame": {"required": ["id"], "nonEmpty": ["id"]},
	"startSugarWheelMinigame": {"required": ["id"], "nonEmpty": ["id"]},
	"startPaperCraftMinigame": {"required": ["id"], "nonEmpty": ["id"]},
	"startPressureHold": {"required": ["id"], "nonEmpty": ["id"]},
	"playSignalCue": {"required": ["id"], "nonEmpty": ["id"]},
	"sugarWheelShowSpeech": {"required": ["role", "text"], "nonEmpty": ["role", "text"], "optional": ["durationMs"]},
	"sugarWheelDismissSpeech": {"required": ["role"], "nonEmpty": ["role"]},
	"sugarWheelDismissAllSpeech": {"required": []},
	"sugarWheelResetPointer": {"required": ["angleDeg"], "optional": ["angle"]},
	"debugAlertActionParams": {"required": [], "optional": ["title"]},
	"damagePlayer": {"required": ["amount"]},
	"healPlayer": {"required": ["amount"]},
	"resetHealth": {"required": []},
	"setHealth": {"required": ["amount"]},
	"incHealth": {"required": ["amount"]},
	"decHealth": {"required": ["amount"]},
	"triggerDeathTether": {"required": []},
	"setSmell": {"required": ["scent"], "nonEmpty": ["scent"], "optional": ["intensity", "dir", "flicker"]},
	"clearSmell": {"required": []},
	"sniff": {"required": []},
	"activatePlane": {"required": ["id"], "nonEmpty": ["id"]},
	"deactivatePlane": {"required": []},
	"showEmote": {"required": ["target", "emote"], "nonEmpty": ["target", "emote"], "optional": ["duration", "anchorOffsetX", "anchorOffsetY"]},
	"showSpeechBubble": {"required": ["target", "text"], "nonEmpty": ["target", "text"], "optional": ["emote", "duration", "anchorOffsetX", "anchorOffsetY"]},
	"showEmoteAndWait": {"required": ["target", "emote"], "nonEmpty": ["target", "emote"], "optional": ["duration", "anchorOffsetX", "anchorOffsetY"]},
	"showSpeechBubbleAndWait": {"required": ["target", "text"], "nonEmpty": ["target", "text"], "optional": ["emote", "duration", "anchorOffsetX", "anchorOffsetY"]},
	"playNpcAnimation": {"required": ["target", "state"], "nonEmpty": ["target", "state"]},
	"setEntityEnabled": {"required": ["target", "enabled"], "nonEmpty": ["target"]},
	"switchScene": {"required": ["targetScene"], "nonEmpty": ["targetScene"], "optional": ["targetSpawnPoint"]},
	"changeScene": {"required": ["targetScene"], "nonEmpty": ["targetScene"], "optional": ["targetSpawnPoint", "cameraX", "cameraY"]},
	"setPlayerAvatar": {"required": [], "optional": ["animManifest", "bundleId", "stateMap", "portraitSlug"]},
	"resetPlayerAvatar": {"required": []},
	"setSceneDepthFloorOffset": {"required": ["floor_offset"]},
	"resetSceneDepthFloorOffset": {"required": []},
	"setCameraZoom": {"required": ["zoom"]},
	"restoreSceneCameraZoom": {"required": []},
	"fadingZoom": {"required": ["zoom"], "optional": ["durationMs", "duration"]},
	"fadingRestoreSceneCameraZoom": {"required": [], "optional": ["durationMs", "duration"]},
	"fadeWorldToBlack": {"required": [], "optional": ["durationMs", "duration"]},
	"fadeWorldFromBlack": {"required": [], "optional": ["durationMs", "duration"]},
	"stopNpcPatrol": {"required": ["npcId"], "nonEmpty": ["npcId"]},
	"persistNpcDisablePatrol": {"required": ["npcId"], "nonEmpty": ["npcId"]},
	"persistNpcEnablePatrol": {"required": ["npcId"], "nonEmpty": ["npcId"]},
	"persistNpcEntityEnabled": {"required": ["target", "enabled"], "nonEmpty": ["target"]},
	"persistHotspotEnabled": {"required": ["sceneId", "hotspotId", "enabled"], "nonEmpty": ["sceneId", "hotspotId"]},
	"setZoneEnabled": {"required": ["sceneId", "zoneId", "enabled"], "nonEmpty": ["sceneId", "zoneId"]},
	"persistZoneEnabled": {"required": ["sceneId", "zoneId", "enabled"], "nonEmpty": ["sceneId", "zoneId"]},
	"setSceneEntityPosition": {"required": ["sceneId", "entityId", "x", "y"], "nonEmpty": ["sceneId", "entityId"], "optional": ["entityKind"]},
	"persistNpcAt": {"required": ["target", "x", "y"], "nonEmpty": ["target"]},
	"persistNpcAnimState": {"required": ["target", "state"], "nonEmpty": ["target", "state"]},
	"persistPlayNpcAnimation": {"required": ["target", "state"], "nonEmpty": ["target", "state"]},
	"showOverlayImage": {"required": ["id", "image", "xPercent", "yPercent", "widthPercent"], "nonEmpty": ["id", "image"]},
	"hideOverlayImage": {"required": ["id"], "nonEmpty": ["id"]},
	"blendOverlayImage": {"required": ["id", "fromImage", "toImage", "xPercent", "yPercent", "widthPercent"], "nonEmpty": ["id", "fromImage", "toImage"], "optional": ["durationMs", "delayMs"]},
	"setHotspotDisplayImage": {"required": ["sceneId", "hotspotId", "image"], "nonEmpty": ["sceneId", "hotspotId", "image"], "optional": ["worldWidth", "worldHeight", "facing"]},
	"tempSetHotspotDisplayFacing": {"required": ["sceneId", "hotspotId", "facing"], "nonEmpty": ["sceneId", "hotspotId", "facing"]},
	"setEntityField": {"required": ["sceneId", "entityKind", "entityId", "fieldName", "value"], "nonEmpty": ["sceneId", "entityKind", "entityId", "fieldName"]},
	"startDialogueGraph": {"required": ["graphId"], "nonEmpty": ["graphId"], "optional": ["entry", "npcId", "ownerType", "ownerId", "dimBackground"]},
	"waitClickContinue": {"required": [], "optional": ["text"]},
	"playScriptedDialogue": {"required": ["lines"], "optional": ["scriptedNpcId", "dimBackground"]},
	"waitMs": {"required": [], "optional": ["durationMs"]},
	"moveEntityTo": {"required": ["target", "x", "y"], "nonEmpty": ["target"], "optional": ["speed", "waypoints", "moveAnimState", "faceTowardMovement", "sceneId"]},
	"faceEntity": {"required": ["target"], "nonEmpty": ["target"], "optional": ["direction", "faceTarget"]},
	"cutsceneSpawnActor": {"required": ["id", "x", "y"], "nonEmpty": ["id"], "optional": ["name"]},
	"cutsceneRemoveActor": {"required": ["id"], "nonEmpty": ["id"]},
	"enableRuleOffers": {"required": ["slots"]},
	"disableRuleOffers": {"required": []},
}


static func is_known_action_type(type: String) -> bool:
	return ACTION_PARAM_MANIFEST.has(type)


static func get_action_param_manifest(type: String) -> Variant:
	return ACTION_PARAM_MANIFEST.get(type) if is_known_action_type(type) else null
