export const WORKSPACE_SCHEMA_VERSION: number;
export const WORKBENCH_DIR_NAME: string;
export const WORKSPACE_FILE_NAME: string;

export function rawAssetsRoot(repoRoot: string): string;
export function characterRoot(repoRoot: string, folderName: string): string;
export function workbenchRoot(repoRoot: string, folderName: string): string;
export function workspaceFile(repoRoot: string, folderName: string): string;
export function listCatalog(repoRoot: string): any[];
export function createWorkspace(repoRoot: string, input: any): any;
export function loadWorkspace(repoRoot: string, folderName: string): any;
export function nodeDefinitions(workspace: any): any[];
export function loadRevision(repoRoot: string, folderName: string, workspace: any, revisionId: string): any;
export function computeNodeStates(repoRoot: string, folderName: string, workspace: any): any[];
export function addAction(repoRoot: string, folderName: string, input: any): any;
export function updateActionSpec(repoRoot: string, folderName: string, actionId: string, patch: any, authority?: string): any;
export function invalidateActionStage(repoRoot: string, folderName: string, stage: string, note?: string, authority?: string): any;
export function setActionEnabled(repoRoot: string, folderName: string, actionId: string, enabled: boolean, authority?: string): any;
export function updateExportTargets(repoRoot: string, folderName: string, input: any, authority?: string): any;
export function submitRevision(repoRoot: string, folderName: string, input: any): any;
export function recordReview(repoRoot: string, folderName: string, input: any): any;
export function registerLegacyBaseline(repoRoot: string, folderName: string, nodeId: string, revisionId: string, authority?: string): any;
export function recordPublication(repoRoot: string, folderName: string, input: any): any;
export function setHead(repoRoot: string, folderName: string, nodeId: string, revisionId: string, authority?: string): any;
export function restoreCompatible(repoRoot: string, folderName: string, nodeId: string, recursive?: boolean, authority?: string): any;
export function createCheckpoint(repoRoot: string, folderName: string, input: any): any;
export function restoreCheckpoint(repoRoot: string, folderName: string, checkpointId: string, authority?: string): any;
export function saveCalibrationDraft(repoRoot: string, folderName: string, calibration: any, authority?: string): any;
export function loadCalibrationDraft(repoRoot: string, folderName: string): any;
export function commitCalibration(repoRoot: string, folderName: string, calibration: any, note?: string, authority?: string): any;
export function auditWorkspace(repoRoot: string, folderName: string, workspace?: any, verifyHashes?: boolean): any;
export function getWorkspaceView(repoRoot: string, folderName: string, workspace?: any): any;
export function resolveArtifactPath(repoRoot: string, folderName: string, revisionId: string, artifactIndex: number): { path: string; artifact: any };
export function writeAgentContext(repoRoot: string, folderName: string, workspace?: any): any;
