from __future__ import annotations

import csv
import html
import json
from collections import defaultdict
from pathlib import Path
from urllib.parse import quote

from .hub import build_governance_hub, compact_hub_for_prompt
from .models import AuditResult, Artifact, Issue


def write_outputs(result: AuditResult, out_dir: Path) -> dict[str, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    registry = out_dir / "registry.json"
    report = out_dir / "report.md"
    dashboard = out_dir / "dashboard.html"
    csv_path = out_dir / "inventory.csv"
    agent_context = out_dir / "agent-context-current.md"

    data = result.to_dict()
    data["workpacks"] = _workpacks(result)
    registry.write_text(json.dumps(data, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    report.write_text(render_markdown(result), encoding="utf-8")
    dashboard.write_text(render_dashboard(result, out_dir), encoding="utf-8")
    write_inventory_csv(result.artifacts, csv_path)
    agent_context.write_text(render_agent_context(result, data), encoding="utf-8")
    return {
        "registry": registry,
        "report": report,
        "dashboard": dashboard,
        "inventory_csv": csv_path,
        "agent_context": agent_context,
    }


def render_markdown(result: AuditResult) -> str:
    lines: list[str] = []
    stats = result.stats
    lines.append("# Skill / Workflow Governance Report")
    lines.append("")
    lines.append(f"- Generated: `{result.generated_at}`")
    lines.append(f"- Root: `{result.root}`")
    lines.append(f"- Artifacts: `{stats['artifact_count']}`")
    lines.append(f"- Issues: `{stats['issue_count']}`")
    lines.append("")

    lines.append("## Summary")
    lines.append("")
    lines.append("### Artifacts By Type")
    lines.append("")
    lines.extend(_kv_lines(stats.get("by_type", {})))
    lines.append("")
    lines.append("### Issues By Severity")
    lines.append("")
    lines.extend(_kv_lines(stats.get("by_severity", {})))
    lines.append("")

    lines.append("## Issues")
    lines.append("")
    if not result.issues:
        lines.append("No issues found.")
    else:
        lines.append("| Severity | Category | Artifact | Evidence | Suggestion |")
        lines.append("|---|---|---|---|---|")
        for issue in result.issues:
            loc = f"{issue.path}:{issue.line}" if issue.line else issue.path
            lines.append(
                "| "
                + " | ".join(
                    [
                        _md(issue.severity),
                        _md(issue.category),
                        _md(loc),
                        _md(issue.evidence),
                        _md(issue.suggestion),
                    ]
                )
                + " |"
            )
    lines.append("")

    lines.append("## Inventory")
    lines.append("")
    lines.append("| Type | ID | Title | Path | Source |")
    lines.append("|---|---|---|---|---|")
    for artifact in result.artifacts:
        lines.append(
            "| "
            + " | ".join(
                [
                    _md(artifact.type),
                    _md(artifact.id),
                    _md(artifact.title),
                    _md(artifact.path),
                    _md(artifact.source),
                ]
            )
            + " |"
        )
    lines.append("")
    return "\n".join(lines)


def render_agent_context(result: AuditResult, registry: dict[str, object]) -> str:
    """A portable context pack that Codex/Claude can read without the dashboard UI."""
    root = Path(result.root).resolve()
    hub = compact_hub_for_prompt(build_governance_hub(root, registry))
    stats = result.stats
    lines: list[str] = [
        "# GameDraft Governance Agent Context",
        "",
        "This file is generated by `python3 -B tools/skill_workflow_governance/govern.py audit`.",
        "Codex, Claude, or another agent client can reference this file directly instead of reading the dashboard page.",
        "",
        "## Client Contract",
        "",
        "- Treat the dashboard as a view only; the canonical machine-readable state is `registry.json` and the `governance://` resources.",
        "- For read-only analysis, do not modify files. For fixes, only edit the files implicated by selected workpacks or evidence.",
        "- After any fix, rerun `python3 -B tools/skill_workflow_governance/govern.py audit` and report remaining risks.",
        "- Do not invent host tools. If an MCP client is connected, use the tools/resources listed below; otherwise read the files named here.",
        "",
        "## Direct Files",
        "",
        "- `tools/skill_workflow_governance/out/registry.json`: full structured audit state.",
        "- `tools/skill_workflow_governance/out/report.md`: human-readable audit report.",
        "- `tools/skill_workflow_governance/out/dashboard.html`: local visual dashboard.",
        "- `tools/skill_workflow_governance/out/agent-context-current.md`: this portable agent context.",
        "",
        "## MCP Server",
        "",
        "```json",
        json.dumps(
            {
                "mcpServers": {
                    "gamedraft-governance": {
                        "command": "python3",
                        "args": [
                            "-B",
                            "tools/skill_workflow_governance/mcp_server.py",
                            str(root),
                        ],
                    }
                }
            },
            ensure_ascii=False,
            indent=2,
        ),
        "```",
        "",
        "## Audit Summary",
        "",
        f"- Generated: `{result.generated_at}`",
        f"- Root: `{result.root}`",
        f"- Artifacts: `{stats.get('artifact_count', 0)}`",
        f"- Issues: `{stats.get('issue_count', 0)}`",
        f"- By severity: `{json.dumps(stats.get('by_severity', {}), ensure_ascii=False)}`",
        f"- By category: `{json.dumps(stats.get('by_category', {}), ensure_ascii=False)}`",
        "",
        "## Governance Resources",
        "",
    ]

    resources = hub.get("resources") if isinstance(hub.get("resources"), list) else []
    for resource in resources:
        if not isinstance(resource, dict):
            continue
        uri = str(resource.get("uri") or "")
        title = str(resource.get("title") or uri)
        summary = str(resource.get("summary") or "")
        count = resource.get("count")
        count_text = f" ({count})" if count is not None else ""
        lines.append(f"- `{uri}`{count_text}: {title}。{summary}")

    lines.extend(["", "## Governance Tools", ""])
    tools = hub.get("tools") if isinstance(hub.get("tools"), list) else []
    for tool in tools:
        if not isinstance(tool, dict):
            continue
        name = str(tool.get("name") or "")
        side_effect = str(tool.get("sideEffect") or "")
        approval = "requires approval" if tool.get("requiresApproval") else "no approval"
        desc = str(tool.get("description") or tool.get("title") or "")
        lines.append(f"- `{name}` [{side_effect}, {approval}]: {desc}")

    lines.extend(["", "## Workpacks", ""])
    workpacks = registry.get("workpacks") if isinstance(registry.get("workpacks"), list) else []
    if not workpacks:
        lines.append("No workpacks found.")
    for pack in workpacks:
        if not isinstance(pack, dict):
            continue
        lines.extend(
            [
                f"### {pack.get('priority', 'P?')} {pack.get('title', pack.get('id', 'workpack'))}",
                "",
                f"- URI: `governance://workpack/{pack.get('id', '')}`",
                f"- Kind: `{pack.get('kind', '')}`",
                f"- Issues: `{pack.get('issue_count', 0)}`",
                f"- Summary: {pack.get('summary', '')}",
                f"- Next: {pack.get('next', '')}",
            ]
        )
        paths = pack.get("paths") if isinstance(pack.get("paths"), list) else []
        if paths:
            lines.append("- Paths:")
            for path in paths[:12]:
                lines.append(f"  - `{path}`")
        prompt = str(pack.get("agent_prompt") or "").strip()
        if prompt:
            lines.extend(["", "Prompt:", "", "```text", prompt, "```"])
        lines.append("")

    lines.extend(
        [
            "## Compact Host Snapshot",
            "",
            "```json",
            json.dumps(hub, ensure_ascii=False, indent=2),
            "```",
            "",
        ]
    )
    return "\n".join(lines)


def render_dashboard(result: AuditResult, out_dir: Path) -> str:
    data = result.to_dict()
    data["workpacks"] = _workpacks(result)
    data["mcp"] = _mcp_client_config(Path(result.root).resolve())
    for artifact in data["artifacts"]:
        artifact["href"] = _source_href(artifact["path"])
    for issue in data["issues"]:
        issue["href"] = _source_href(issue["path"], issue.get("line") or 0)
    payload = json.dumps(data, ensure_ascii=False).replace("</", "<\\/")
    template = DASHBOARD_HTML.replace("{{", "{").replace("}}", "}")
    return template.replace("%DATA_JSON%", payload)


def _mcp_client_config(root: Path) -> dict[str, object]:
    python = root / ".tools" / "venv" / "bin" / "python"
    python_command = str(python) if python.exists() else "python3"
    launcher = root / "tools" / "skill_workflow_governance" / "mcp_server.py"
    stdio_command = [python_command, "-B", str(launcher), str(root)]
    return {
        "serverName": "gamedraft-governance",
        "root": str(root),
        "command": python_command,
        "args": ["-B", str(launcher), str(root)],
        "stdioCommand": stdio_command,
        "codexInstall": _shell_join(
            [
                "/Applications/Codex.app/Contents/Resources/codex",
                "mcp",
                "add",
                "gamedraft-governance",
                "--",
                *stdio_command,
            ]
        ),
        "claudeCodeInstall": _shell_join(
            [
                "claude",
                "mcp",
                "add",
                "--scope",
                "user",
                "gamedraft-governance",
                "--",
                *stdio_command,
            ]
        ),
        "claudeDesktopConfig": {
            "mcpServers": {
                "gamedraft-governance": {
                    "command": python_command,
                    "args": ["-B", str(launcher), str(root)],
                }
            }
        },
    }


def _shell_join(parts: list[str]) -> str:
    def quote(part: str) -> str:
        if not part:
            return "''"
        safe = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789_+-=./:"
        if all(char in safe for char in part):
            return part
        return "'" + part.replace("'", "'\"'\"'") + "'"

    return " ".join(quote(str(part)) for part in parts)


def _workpacks(result: AuditResult) -> list[dict[str, object]]:
    issues_by_category: dict[str, list[Issue]] = defaultdict(list)
    for issue in result.issues:
        issues_by_category[issue.category].append(issue)

    artifact_by_id = {artifact.id: artifact for artifact in result.artifacts}
    config = {
        "broken-reference": {
            "priority": "P0",
            "title": "断链修复包",
            "kind": "agent-fix",
            "summary": "缺失引用集中处理，不要逐条手改。按文件分组检查改名、移动、删除三种情况。",
            "next": "交给 agent 执行：能确定的路径直接修；明显过期的引用删；无法判断的只列成确认清单。",
        },
        "drift-risk": {
            "priority": "P1",
            "title": "规则漂移复核包",
            "kind": "agent-review",
            "summary": "规则/工作流引用的代码或文档更新过，说明文字可能已经落后。",
            "next": "交给 agent 对比规则和当前实现：过时就改规则，仍然正确就标记已验证。",
        },
        "missing-metadata": {
            "priority": "P1",
            "title": "Skill 触发条件补齐包",
            "kind": "agent-edit",
            "summary": "Skill 没写清什么时候该用，容易让 Codex 和 Claude 误触发或漏触发。",
            "next": "交给 agent 批量补 when-to-use / when-not-to-use，不改变 skill 正文语义。",
        },
        "missing-lifecycle": {
            "priority": "P2",
            "title": "生命周期元数据补齐包",
            "kind": "batch-edit",
            "summary": "缺少 status / owner / last verified 这类治理字段，可以标准化批量补。",
            "next": "交给 agent 批量插入统一生命周期块，默认 owner 为 shared，验证日期用本次审计日期。",
        },
        "stale-candidate": {
            "priority": "P2",
            "title": "疑似过期归档包",
            "kind": "agent-review",
            "summary": "长期没变的规则或工作流不一定错，但需要确认还在不在用。",
            "next": "交给 agent 查引用和最近使用痕迹：仍在用则补验证记录，不再用则建议归档。",
        },
        "weak-workflow-entry": {
            "priority": "P2",
            "title": "工作流入口补齐包",
            "kind": "agent-edit",
            "summary": "工作流文档没有明显脚本、工具或检查入口，后续 agent 很难执行。",
            "next": "交给 agent 给每个工作流补入口链接、命令或标记为背景资料。",
        },
        "possible-overlap": {
            "priority": "P3",
            "title": "Skill 重叠边界包",
            "kind": "agent-review",
            "summary": "相似 skill 可能职责重叠，先确认边界，再决定合并、拆分或互链。",
            "next": "交给 agent 比较触发条件，只输出边界建议和候选改法，不直接大改。",
        },
    }

    priority_order = {"P0": 0, "P1": 1, "P2": 2, "P3": 3}
    packs: list[dict[str, object]] = []
    for category, issues in issues_by_category.items():
        meta = config.get(
            category,
            {
                "priority": "P3",
                "title": category,
                "kind": "review",
                "summary": "未分类治理项，先作为证据保留。",
                "next": "交给 agent 归类后再决定是否处理。",
            },
        )
        affected = sorted({issue.path for issue in issues})
        issue_ids = [issue.id for issue in issues]
        artifact_types = sorted(
            {
                artifact_by_id[issue.artifact_id].type
                for issue in issues
                if issue.artifact_id in artifact_by_id
            }
        )
        prompt = _agent_prompt(
            title=str(meta["title"]),
            category=category,
            summary=str(meta["summary"]),
            next_action=str(meta["next"]),
            paths=affected,
            issue_count=len(issues),
        )
        packs.append(
            {
                "id": category,
                "priority": meta["priority"],
                "title": meta["title"],
                "kind": meta["kind"],
                "summary": meta["summary"],
                "next": meta["next"],
                "issue_count": len(issues),
                "artifact_count": len(affected),
                "artifact_types": artifact_types,
                "paths": affected[:12],
                "hidden_path_count": max(0, len(affected) - 12),
                "issue_ids": issue_ids,
                "sample_issues": [_issue_sample(issue) for issue in issues[:6]],
                "agent_prompt": prompt,
            }
        )
    return sorted(packs, key=lambda pack: (priority_order.get(str(pack["priority"]), 9), -int(pack["issue_count"]), str(pack["title"])))


def _issue_sample(issue: Issue) -> dict[str, object]:
    return {
        "id": issue.id,
        "severity": issue.severity,
        "path": issue.path,
        "line": issue.line,
        "title": issue.title,
        "evidence": issue.evidence,
        "href": _source_href(issue.path, issue.line),
    }


def _agent_prompt(
    *,
    title: str,
    category: str,
    summary: str,
    next_action: str,
    paths: list[str],
    issue_count: int,
) -> str:
    shown = "\n".join(f"- {path}" for path in paths[:20])
    more = f"\n- ...还有 {len(paths) - 20} 个文件，详见 dashboard/registry.json" if len(paths) > 20 else ""
    return (
        f"请处理 GameDraft Skill/Workflow 治理包：{title}（{category}，{issue_count} 项）。\n"
        f"目标：{summary}\n"
        f"执行方式：{next_action}\n"
        "要求：不要逐条问用户；先按文件分组，能自动修的直接修，无法判断的最后汇总成不超过 5 条确认项；完成后运行 "
        "`python3 -B tools/skill_workflow_governance/govern.py audit` 验证。\n"
        f"涉及文件：\n{shown}{more}"
    )


DASHBOARD_HTML = """<!doctype html>
<html lang="zh-CN">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>Skill / Workflow 治理台</title>
  <style>
    :root {{
      color-scheme: light;
      --bg: #f6f7f9;
      --panel: #ffffff;
      --ink: #202124;
      --muted: #62656a;
      --line: #d9dde5;
      --soft: #eef1f5;
      --accent: #17634f;
      --error: #b3261e;
      --warn: #946200;
      --info: #3f5f8f;
    }}
    * {{ box-sizing: border-box; }}
    body {{
      margin: 0;
      background: var(--bg);
      color: var(--ink);
      font: 14px/1.45 -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
    }}
    header {{
      padding: 18px 28px 14px;
      border-bottom: 1px solid var(--line);
      background: #fbfcfd;
      position: sticky;
      top: 0;
      z-index: 2;
    }}
    h1 {{ margin: 0 0 6px; font-size: 22px; }}
    .meta {{ color: var(--muted); display: flex; flex-wrap: wrap; gap: 14px; font-size: 12px; }}
    main {{ padding: 22px 28px 40px; max-width: 1840px; margin: 0 auto; }}
    .layout {{ display: block; }}
    .governance-main {{ min-width: 0; }}
    .cards {{ display: grid; grid-template-columns: repeat(4, minmax(160px, 1fr)); gap: 12px; margin-bottom: 18px; }}
    .card {{ background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 14px; }}
    .card b {{ font-size: 24px; display: block; }}
    .card span {{ color: var(--muted); }}
    .board {{ display: grid; grid-template-columns: minmax(0, 1fr); gap: 12px; }}
    .pack {{ background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 14px; }}
    .pack-head {{ display: flex; justify-content: space-between; gap: 12px; align-items: flex-start; }}
    .pack-title {{ display: flex; align-items: center; gap: 8px; flex-wrap: wrap; }}
    .pack h3 {{ margin: 0; font-size: 16px; }}
    .pack p {{ margin: 8px 0; max-width: 980px; }}
    .priority {{ border-radius: 999px; padding: 2px 8px; font-weight: 700; font-size: 12px; background: var(--soft); }}
    .p-P0 {{ color: var(--error); }}
    .p-P1 {{ color: var(--warn); }}
    .p-P2,.p-P3 {{ color: var(--info); }}
    .counts {{ color: var(--muted); white-space: nowrap; }}
    .next {{ background: #f3f7f5; border-left: 3px solid var(--accent); padding: 8px 10px; border-radius: 5px; }}
    .paths {{ display: flex; flex-wrap: wrap; gap: 6px; margin: 8px 0 4px; }}
    .toolbar {{ display: flex; gap: 10px; flex-wrap: wrap; margin: 14px 0; }}
    input, select {{
      border: 1px solid var(--line);
      border-radius: 6px;
      padding: 8px 10px;
      background: white;
      color: var(--ink);
    }}
    input {{ min-width: 280px; flex: 1; }}
    table {{ width: 100%; border-collapse: collapse; background: var(--panel); border: 1px solid var(--line); }}
    th, td {{ border-bottom: 1px solid var(--line); padding: 8px 10px; vertical-align: top; text-align: left; }}
    th {{ background: #f0f2f5; position: sticky; top: 75px; z-index: 1; }}
    tr:hover td {{ background: #fafafa; }}
    a {{ color: var(--accent); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .pill {{ display: inline-block; border: 1px solid var(--line); border-radius: 999px; padding: 1px 7px; color: var(--muted); margin: 1px 3px 1px 0; }}
    .sev-error {{ color: var(--error); font-weight: 700; }}
    .sev-warn {{ color: var(--warn); font-weight: 700; }}
    .sev-info {{ color: var(--info); font-weight: 700; }}
    section {{ margin-top: 26px; }}
    h2 {{ margin: 0 0 10px; font-size: 18px; }}
    button {{
      border: 1px solid var(--line);
      background: white;
      border-radius: 6px;
      padding: 7px 10px;
      margin-right: 6px;
      cursor: pointer;
    }}
    button:hover {{ background: var(--soft); }}
    .ref-btn {{ padding: 3px 7px; font-size: 12px; margin: 3px 4px 0 0; }}
    details {{ background: var(--panel); border: 1px solid var(--line); border-radius: 8px; padding: 10px 12px; }}
    summary {{ cursor: pointer; font-weight: 700; }}
    .status {{ color: var(--muted); font-size: 12px; }}
    .copied {{ color: var(--accent); font-size: 12px; margin-left: 8px; }}
    .mcp-panel {{ margin: 0 0 14px; }}
    .mcp-actions {{ display: flex; flex-wrap: wrap; gap: 8px; margin: 10px 0; }}
    .mcp-actions button {{ margin: 0; }}
    .mcp-preview {{ white-space: pre-wrap; overflow: auto; max-height: 180px; border: 1px solid var(--line); border-radius: 6px; background: #fbfcfd; padding: 10px; font: 12px Menlo,Consolas,monospace; }}
    @media (max-width: 1180px) {{
      .layout {{ grid-template-columns: 1fr; }}
      .cards {{ grid-template-columns: repeat(2, minmax(140px, 1fr)); }}
      th {{ position: static; }}
      .pack-head {{ display: block; }}
      .counts {{ white-space: normal; margin-top: 8px; }}
    }}
  </style>
</head>
<body>
  <header>
    <h1>Skill / Workflow 治理台</h1>
    <div class="meta">
      <span id="generated"></span>
      <span id="root"></span>
      <span><a href="agent-context-current.md">Agent Context</a></span>
      <span><a href="registry.json">Registry JSON</a></span>
      <span id="copyStatus"></span>
    </div>
  </header>
  <main>
    <details class="mcp-panel" open data-ref-uri="governance://view/mcp-install">
      <summary>MCP 安装 / 状态 <span class="status" id="mcpStatus">checking</span></summary>
      <div class="status">安装一次后，新开的 Codex / Claude 会话就能解析 governance:// 引用。当前页面会做一次 MCP 自检，但 stdio MCP 是由客户端按配置启动的。</div>
      <div class="mcp-actions">
        <button id="copyMcpAll">复制全部安装说明</button>
        <button id="copyMcpCodex">复制 Codex 命令</button>
        <button id="copyMcpClaude">复制 Claude Code 命令</button>
        <button id="copyMcpClaudeDesktop">复制 Claude Desktop 配置</button>
      </div>
      <pre class="mcp-preview" id="mcpPreview"></pre>
    </details>
    <div class="cards" id="cards" data-ref-uri="governance://view/cards"></div>
    <div class="layout">
      <div class="governance-main">
        <section data-ref-uri="governance://view/workpacks">
          <h2>治理包</h2>
          <div class="board" id="workpacks"></div>
        </section>
        <section data-ref-uri="governance://view/issues">
          <details>
            <summary>证据库：原始问题列表</summary>
            <div class="toolbar">
              <input id="issueSearch" placeholder="搜索问题、路径、证据">
              <select id="severityFilter"><option value="">全部级别</option></select>
              <select id="categoryFilter"><option value="">全部类别</option></select>
            </div>
            <table>
              <thead><tr><th>URI</th><th>级别</th><th>类别</th><th>位置</th><th>证据</th><th>建议</th></tr></thead>
              <tbody id="issues"></tbody>
            </table>
          </details>
        </section>
        <section data-ref-uri="governance://view/artifacts">
          <details>
            <summary>资产清单</summary>
            <div class="toolbar">
              <input id="artifactSearch" placeholder="搜索清单、标题、路径">
              <select id="typeFilter"><option value="">全部类型</option></select>
            </div>
            <table>
              <thead><tr><th>类型</th><th>标题</th><th>路径</th><th>来源</th><th>提示</th></tr></thead>
              <tbody id="artifacts"></tbody>
            </table>
          </details>
        </section>
      </div>
    </div>
  </main>
  <script>
    const DATA = %DATA_JSON%;
    const $ = (id) => document.getElementById(id);
    const esc = (s) => String(s ?? '').replace(/[&<>"']/g, c => ({{'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}}[c]));
    const MCP = DATA.mcp || {{}};
    function uniq(arr) {{ return [...new Set(arr.filter(Boolean))].sort(); }}
    function optionize(select, values) {{ for (const v of values) select.insertAdjacentHTML('beforeend', `<option value="${{esc(v)}}">${{esc(v)}}</option>`); }}
    function includes(row, q) {{ return JSON.stringify(row).toLowerCase().includes(q.toLowerCase()); }}
    function uriPart(value) {{ return encodeURIComponent(String(value ?? '').trim()); }}
    function canonicalUri(type, id) {{
      if(type === 'workpack') return `governance://workpack/${{uriPart(id)}}`;
      if(type === 'issue') return `governance://issue/${{uriPart(id)}}`;
      if(type === 'artifact') return `governance://artifact/${{uriPart(id)}}`;
      if(type === 'stat') return `governance://stat/${{uriPart(id)}}`;
      if(type === 'view') return `governance://view/${{uriPart(id)}}`;
      if(type === 'source') return `governance://source/${{uriPart(id)}}`;
      return '';
    }}
    async function copyReference(uri) {{
      if(!uri) return;
      try {{
        if(navigator.clipboard) await navigator.clipboard.writeText(uri);
        else fallbackCopy(uri);
      }} catch {{
        fallbackCopy(uri);
      }}
      const status = $('copyStatus');
      if(status) {{
        status.textContent = `已复制 URI：${{uri}}`;
        setTimeout(() => {{ if(status.textContent === `已复制 URI：${{uri}}`) status.textContent = ''; }}, 1600);
      }}
    }}
    function addRef(type, id, uri='') {{
      copyReference(uri || canonicalUri(type, id));
    }}
    function installText(kind='all') {{
      const desktopConfig = JSON.stringify(MCP.claudeDesktopConfig || {{}}, null, 2);
      const parts = [];
      if(kind === 'all' || kind === 'codex') {{
        parts.push(`# Codex\\n${{MCP.codexInstall || ''}}\\n# 然后重开 Codex 会话，问它读取 governance://hub`);
      }}
      if(kind === 'all' || kind === 'claude') {{
        parts.push(`# Claude Code\\n${{MCP.claudeCodeInstall || ''}}\\n# 然后重开 Claude Code 会话，问它读取 governance://hub`);
      }}
      if(kind === 'all' || kind === 'desktop') {{
        parts.push(`# Claude Desktop\\n把下面这段合并到 ~/Library/Application Support/Claude/claude_desktop_config.json 的顶层，然后完全退出并重启 Claude Desktop：\\n${{desktopConfig}}`);
      }}
      parts.push(`# 用法\\n安装并重开客户端后，聊天里只需要粘裸 URI，例如：\\ngovernance://source/.cursor%2Fskills%2Fadd-text-ref%2FSKILL.md\\n\\n如果临时没接 MCP，再让 agent 读取：\\n- tools/skill_workflow_governance/out/agent-context-current.md\\n- tools/skill_workflow_governance/out/registry.json`);
      return parts.join('\\n\\n');
    }}
    async function copyInstall(kind) {{
      const text = installText(kind);
      try {{
        if(navigator.clipboard) await navigator.clipboard.writeText(text);
        else fallbackCopy(text);
      }} catch {{
        fallbackCopy(text);
      }}
      const status = $('copyStatus');
      if(status) status.textContent = '已复制 MCP 安装说明';
    }}
    async function refreshMcpStatus() {{
      const preview = $('mcpPreview');
      if(preview) preview.textContent = installText('all');
      try {{
        const response = await fetch('/api/governance/mcp');
        const data = await response.json();
        const text = data.ok ? `ready · ${{data.resourceCount || 0}} resources` : `failed · ${{data.message || 'unknown'}}`;
        $('mcpStatus').textContent = text;
      }} catch (err) {{
        $('mcpStatus').textContent = `status unavailable · ${{err}}`;
      }}
    }}
    function fallbackCopy(text) {{
      const area = document.createElement('textarea');
      area.value = text;
      area.style.position = 'fixed';
      area.style.left = '-9999px';
      document.body.appendChild(area);
      area.focus();
      area.select();
      document.execCommand('copy');
      area.remove();
    }}
    async function copyPack(id) {{
      const pack = DATA.workpacks.find(p => p.id === id);
      if(!pack) return;
      try {{
        if(navigator.clipboard) await navigator.clipboard.writeText(pack.agent_prompt);
        else fallbackCopy(pack.agent_prompt);
      }} catch {{
        fallbackCopy(pack.agent_prompt);
      }}
      const el = document.querySelector(`[data-copied="${{CSS.escape(id)}}"]`);
      if(el) {{
        el.textContent = '已复制';
        setTimeout(() => el.textContent = '', 1400);
      }}
    }}
    function renderCards() {{
      const stats = DATA.stats;
      const sev = stats.by_severity || {{}};
      $('cards').innerHTML = [
        ['治理包', DATA.workpacks.length, 'workpack-count'],
        ['证据项', stats.issue_count, 'issue-count'],
        ['断链/错误', sev.error || 0, 'error-count'],
        ['需复核', sev.warn || 0, 'warn-count'],
      ].map(([label, value, id]) => `
        <div class="card" data-ref-uri="${{esc(canonicalUri('stat', id))}}">
          <b>${{value}}</b><span>${{label}}</span><br>
          <button class="ref-btn" onclick="copyReference('${{esc(canonicalUri('stat', id))}}')">复制 URI</button>
        </div>
      `).join('');
    }}
    function renderWorkpacks() {{
      $('workpacks').innerHTML = DATA.workpacks.map(pack => `
        <article class="pack" data-ref-uri="${{esc(canonicalUri('workpack', pack.id))}}">
          <div class="pack-head">
            <div>
              <div class="pack-title">
                <span class="priority p-${{esc(pack.priority)}}">${{esc(pack.priority)}}</span>
                <h3>${{esc(pack.title)}}</h3>
                <span class="pill">${{esc(pack.kind)}}</span>
              </div>
              <p>${{esc(pack.summary)}}</p>
            </div>
            <div class="counts">${{pack.issue_count}} 项证据 / ${{pack.artifact_count}} 个文件</div>
          </div>
          <div class="next">${{esc(pack.next)}}</div>
          <div class="paths">
            ${{(pack.paths || []).map(p => `<span class="pill" data-ref-uri="${{esc(canonicalUri('source', p))}}"><a href="${{esc(sourceHref(p))}}">${{esc(p)}}</a> <button class="ref-btn" onclick="copyReference('${{esc(canonicalUri('source', p))}}')">URI</button></span>`).join('')}}
            ${{pack.hidden_path_count ? `<span class="pill">还有 ${{pack.hidden_path_count}} 个</span>` : ''}}
          </div>
          <button onclick="copyReference('${{esc(canonicalUri('workpack', pack.id))}}')">复制 URI</button>
          <button onclick="copyPack('${{esc(pack.id)}}')">复制任务文本</button>
          <span class="copied" data-copied="${{esc(pack.id)}}"></span>
          <details style="margin-top:10px">
            <summary>查看样例证据</summary>
            <table>
              <tbody>${{(pack.sample_issues || []).map(i => `
                <tr data-ref-uri="${{esc(canonicalUri('issue', i.id))}}"><td><button class="ref-btn" onclick="copyReference('${{esc(canonicalUri('issue', i.id))}}')">URI</button></td><td class="sev-${{esc(i.severity)}}">${{esc(i.severity)}}</td><td><a data-ref-uri="${{esc(canonicalUri('source', i.path))}}" href="${{esc(i.href)}}">${{esc(i.path)}}:${{esc(i.line)}}</a></td><td>${{esc(i.evidence)}}</td></tr>
              `).join('')}}</tbody>
            </table>
          </details>
        </article>
      `).join('');
    }}
    function sourceHref(path) {{ return `/governance/source?path=${{encodeURIComponent(path)}}`; }}
    function renderIssues() {{
      const q = $('issueSearch').value;
      const sev = $('severityFilter').value;
      const cat = $('categoryFilter').value;
      const rows = DATA.issues.filter(i => (!sev || i.severity === sev) && (!cat || i.category === cat) && (!q || includes(i, q)));
      $('issues').innerHTML = rows.map(i => `
        <tr data-ref-uri="${{esc(canonicalUri('issue', i.id))}}">
          <td><button class="ref-btn" onclick="copyReference('${{esc(canonicalUri('issue', i.id))}}')">URI</button></td>
          <td class="sev-${{esc(i.severity)}}">${{esc(i.severity)}}</td>
          <td>${{esc(i.category)}}</td>
          <td><a data-ref-uri="${{esc(canonicalUri('source', i.path))}}" href="${{esc(i.href)}}">${{esc(i.path)}}:${{esc(i.line)}}</a><br><span class="status">${{esc(i.artifact_id)}}</span></td>
          <td>${{esc(i.evidence)}}</td>
          <td>${{esc(i.suggestion)}}</td>
        </tr>`).join('');
    }}
    function renderArtifacts() {{
      const q = $('artifactSearch').value;
      const type = $('typeFilter').value;
      const rows = DATA.artifacts.filter(a => (!type || a.type === type) && (!q || includes(a, q)));
      $('artifacts').innerHTML = rows.map(a => `
        <tr data-ref-uri="${{esc(canonicalUri('artifact', a.id))}}">
          <td><button class="ref-btn" onclick="copyReference('${{esc(canonicalUri('artifact', a.id))}}')">URI</button><br>${{esc(a.type)}}</td>
          <td><b>${{esc(a.title)}}</b><br><span class="status">${{esc(a.id)}}</span></td>
          <td><a data-ref-uri="${{esc(canonicalUri('source', a.path))}}" href="${{esc(a.href)}}">${{esc(a.path)}}</a></td>
          <td>${{esc(a.source)}}</td>
          <td>${{(a.tags || []).map(t => `<span class="pill">${{esc(t)}}</span>`).join('')}}${{a.trigger_hints?.length ? '<br><span class="status">trigger hints: ' + a.trigger_hints.length + '</span>' : ''}}</td>
        </tr>`).join('');
    }}
    $('generated').textContent = `Generated: ${{DATA.generated_at}}`;
    $('root').textContent = `Root: ${{DATA.root}}`;
    optionize($('severityFilter'), uniq(DATA.issues.map(i => i.severity)));
    optionize($('categoryFilter'), uniq(DATA.issues.map(i => i.category)));
    optionize($('typeFilter'), uniq(DATA.artifacts.map(a => a.type)));
    for (const id of ['issueSearch','severityFilter','categoryFilter']) $(id).addEventListener('input', renderIssues);
    for (const id of ['artifactSearch','typeFilter']) $(id).addEventListener('input', renderArtifacts);
    $('copyMcpAll').addEventListener('click', () => copyInstall('all'));
    $('copyMcpCodex').addEventListener('click', () => copyInstall('codex'));
    $('copyMcpClaude').addEventListener('click', () => copyInstall('claude'));
    $('copyMcpClaudeDesktop').addEventListener('click', () => copyInstall('desktop'));
    renderCards(); renderWorkpacks(); renderIssues(); renderArtifacts();
    refreshMcpStatus();
  </script>
</body>
</html>
"""


def write_inventory_csv(artifacts: list[Artifact], csv_path: Path) -> None:
    with csv_path.open("w", encoding="utf-8", newline="") as f:
        writer = csv.writer(f)
        writer.writerow(["id", "type", "title", "path", "source", "modified", "summary"])
        for artifact in artifacts:
            writer.writerow([artifact.id, artifact.type, artifact.title, artifact.path, artifact.source, artifact.modified, artifact.summary])


def _kv_lines(data: object) -> list[str]:
    if not isinstance(data, dict) or not data:
        return ["- none"]
    return [f"- `{key}`: `{value}`" for key, value in sorted(data.items())]


def _md(text: object) -> str:
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def _source_href(path: str, line: int = 0) -> str:
    suffix = f"&line={line}#L{line}" if line else ""
    return f"/governance/source?path={quote(path)}{suffix}"
