extends Node

var zones_seen: Array = []


func _ready() -> void:
	var patrol_calls: Array = []; var repository := ProjectSettings.globalize_path("res://").trim_suffix("/").get_base_dir(); var assets := RuntimeAssetManager.new({}, RuntimeResourceLocator.new(RuntimeResourceLocator.DEVELOPMENT, repository)); var events := RuntimeEventBus.new(); var flags := RuntimeFlagStore.new(events); var input := RuntimeInputManager.new(); var executor := RuntimeActionExecutor.new(events, flags); var renderer := RuntimeRenderer.new(); add_child(renderer); renderer.set_asset_manager(assets); renderer.init(); var camera := RuntimeCamera.new(renderer.world_container); camera.set_screen_size(800, 600); var player := RuntimePlayer.new(input); renderer.entity_layer.add_child(player.sprite); var scenes := RuntimeSceneManager.new(assets, events, renderer); add_child(scenes); scenes.init({}); preload("res://tests/support/scene_manager_wiring.gd").bind(scenes, player, camera); scenes.set_zone_setter(func(value: Array) -> void: zones_seen = value.duplicate(true)); var adapter := preload("res://tests/support/entity_action_adapter.gd").new(scenes, assets)
	preload("res://tests/support/action_registry_fixture.gd").register(executor, {
		"sceneManager": scenes,
		"resolveActor": func(id: String) -> Variant: return player if id == "player" else scenes.get_npc_by_id(id),
		"setSceneEntityField": Callable(adapter, "set_scene_entity_field"),
		"setHotspotDisplayImage": Callable(adapter, "set_hotspot_display_image"),
		"tempSetHotspotDisplayFacing": Callable(adapter, "temp_set_hotspot_display_facing"),
		"stopNpcPatrol": func(id: String) -> void: patrol_calls.push_back("stop:" + id),
		"startNpcPatrol": func(id: String) -> void: patrol_calls.push_back("start:" + id),
	})
	assert(await scenes.load_scene("test_room_a")); var npc: RuntimeNpc = scenes.get_npc_by_id("npc_ringboy")
	await executor.execute_await({"type": "stopNpcPatrol", "params": {"npcId": "npc_ringboy"}}); assert(patrol_calls == ["stop:npc_ringboy"])
	await executor.execute_await({"type": "persistNpcDisablePatrol", "params": {"npcId": "npc_ringboy"}}); assert(scenes.is_npc_patrol_persistently_disabled("npc_ringboy") and patrol_calls[-1] == "stop:npc_ringboy"); scenes.unload_scene(); assert(await scenes.load_scene("test_room_a")); await executor.execute_await({"type": "persistNpcEnablePatrol", "params": {"npcId": "npc_ringboy"}}); assert(patrol_calls[-1] == "start:npc_ringboy")
	npc = scenes.get_npc_by_id("npc_ringboy"); await executor.execute_await({"type": "playNpcAnimation", "params": {"target": "npc_ringboy", "state": "boy_walk"}}); assert(npc.sprite.get_current_state() == "boy_walk"); await executor.execute_await({"type": "persistNpcAnimState", "params": {"target": "npc_ringboy", "state": "idle"}}); assert(npc.sprite.get_current_state() == "idle" and scenes.get_entity_runtime_override("test_room_a", "npc", "npc_ringboy").animState == "idle")
	await executor.execute_await({"type": "persistNpcAt", "params": {"target": "npc_ringboy", "x": 123, "y": 456}}); assert(npc.get_x() == 123 and npc.get_y() == 456); await executor.execute_await({"type": "setSceneEntityPosition", "params": {"sceneId": "test_room_a", "entityKind": "npc", "entityId": "npc_ringboy", "x": 11.126, "y": 22.239}}); assert(npc.get_x() == 11.13 and npc.get_y() == 22.24)
	await executor.execute_await({"type": "setEntityEnabled", "params": {"target": "npc_ringboy", "enabled": "0"}}); assert(not npc.container.visible); await executor.execute_await({"type": "setEntityEnabled", "params": {"target": "npc_ringboy", "enabled": "true"}}); assert(npc.container.visible); await executor.execute_await({"type": "persistNpcEntityEnabled", "params": {"target": "npc_ringboy", "enabled": false}}); assert(not npc.container.visible)
	var hotspot: RuntimeHotspot = scenes.get_current_hotspots()[0]; await executor.execute_await({"type": "setSceneEntityPosition", "params": {"sceneId": "test_room_a", "entityKind": "hotspot", "entityId": hotspot.get_id(), "x": 33, "y": 44}}); assert(hotspot.get_center_x() == 33 and hotspot.get_center_y() == 44); await executor.execute_await({"type": "persistHotspotEnabled", "params": {"sceneId": "test_room_a", "hotspotId": hotspot.get_id(), "enabled": false}}); assert(not hotspot.container.visible)
	await executor.execute_await({"type": "setHotspotDisplayImage", "params": {"sceneId": "test_room_a", "hotspotId": hotspot.get_id(), "image": "/resources/runtime/images/illustrations/糖画摊_45度_生肖转盘.png", "worldHeight": 50, "facing": "left"}}); assert(hotspot.has_depth_display_image() and hotspot.get_world_size().height == 50 and hotspot.get_world_size().width > 0 and hotspot.get_facing() == -1); await executor.execute_await({"type": "tempSetHotspotDisplayFacing", "params": {"sceneId": "test_room_a", "hotspotId": hotspot.get_id(), "facing": "right"}}); assert(hotspot.get_facing() == 1); await executor.execute_await({"type": "tempSetHotspotDisplayFacing", "params": {"sceneId": "test_room_a", "hotspotId": hotspot.get_id(), "facing": "restore"}}); assert(hotspot.get_facing() == -1)
	await executor.execute_await({"type": "setEntityField", "params": {"sceneId": "test_room_a", "entityKind": "hotspot", "entityId": hotspot.get_id(), "fieldName": "enabled", "value": true}}); assert(hotspot.container.visible)
	scenes.unload_scene(); assert(await scenes.load_scene("码头白天")); var all_zone_count := zones_seen.size(); assert(all_zone_count == 3); await executor.execute_await({"type": "setZoneEnabled", "params": {"sceneId": "码头白天", "zoneId": "new_zone_2", "enabled": false}}); assert(zones_seen.size() == 2); await executor.execute_await({"type": "persistZoneEnabled", "params": {"sceneId": "码头白天", "zoneId": "new_zone_2", "enabled": false}}); await executor.execute_await({"type": "setZoneEnabled", "params": {"sceneId": "码头白天", "zoneId": "new_zone_2", "enabled": true}}); assert(zones_seen.size() == 2); await executor.execute_await({"type": "persistZoneEnabled", "params": {"sceneId": "码头白天", "zoneId": "new_zone_2", "enabled": true}}); assert(zones_seen.size() == 3)
	for type: String in ["playNpcAnimation", "setEntityEnabled", "stopNpcPatrol", "persistNpcDisablePatrol", "persistNpcEnablePatrol", "persistNpcEntityEnabled", "persistHotspotEnabled", "setZoneEnabled", "persistZoneEnabled", "setSceneEntityPosition", "persistNpcAt", "persistNpcAnimState", "persistPlayNpcAnimation", "setHotspotDisplayImage", "tempSetHotspotDisplayFacing", "setEntityField"]: assert(executor.has_handler(type))
	scenes.destroy(); remove_child(scenes); scenes.free(); player.destroy_player(); input.destroy(); input.free(); assets.dispose(); renderer.destroy(); remove_child(renderer); renderer.free(); executor.destroy(); flags.destroy(); events.clear()
	print("Entity/patrol/override Action contract test: PASS"); get_tree().quit(0)
