extends Node


func _ready() -> void:
	var repository := ProjectSettings.globalize_path("res://").trim_suffix("/").get_base_dir(); var assets := RuntimeAssetManager.new(RuntimeResourceLocator.new(RuntimeResourceLocator.DEVELOPMENT, repository)); var events := RuntimeEventBus.new(); var audio := RuntimeAudioManager.new(events); add_child(audio); audio.init({"assetManager": assets}); assert(audio.load_config() and events.listener_count() >= 30)
	assert(audio.serialize() == {"bgmVolume": 0.6, "sfxVolume": 0.8, "ambientVolume": 0.4}); audio.set_volume("bgm", 2.0); audio.set_volume("sfx", -1.0); audio.set_volume("ambient", 0.25); assert(audio.get_volume("bgm") == 1.0 and audio.get_volume("sfx") == 0.0 and audio.get_volume("ambient") == 0.25); audio.deserialize({"bgmVolume": 0.5, "sfxVolume": 0.75, "ambientVolume": 0.2}); assert(audio.serialize() == {"bgmVolume": 0.5, "sfxVolume": 0.75, "ambientVolume": 0.2})
	assert(audio.play_bgm("bgm_placeholder_low_tension", 0)); var bgm_instance := audio.current_bgm.get_instance_id(); assert(audio.play_bgm("bgm_placeholder_low_tension", 0) and audio.current_bgm.get_instance_id() == bgm_instance and audio.get_current_bgm_id() == "bgm_placeholder_low_tension")
	var fading_out: AudioStreamPlayer = audio.current_bgm; assert(audio.play_bgm("bgm_placeholder_dark_shadows", 1000)); var fading_in: AudioStreamPlayer = audio.current_bgm; OS.delay_msec(250); audio.get_debug_output_state()
	var fade_in_linear := db_to_linear(fading_in.volume_db); var fade_out_linear := db_to_linear(fading_out.volume_db); assert(fade_in_linear > 0.08 and fade_in_linear < 0.18 and fade_out_linear > 0.30 and fade_out_linear < 0.45)
	assert(audio.add_ambient("teahouse_roomtone", 0.5)); audio.set_volume("ambient", 0.2); assert(is_equal_approx(db_to_linear(audio.ambient_layers.teahouse_roomtone.volume_db), 0.1)); assert(audio.get_active_ambient_ids() == ["teahouse_roomtone"])
	var refs := audio.get_scene_audio_refs("bgm_placeholder_low_tension", ["teahouse_roomtone", "missing"]); assert(refs.size() == 2 and refs[0].type == "audio" and refs[1].options.loop == true)
	audio.begin_cutscene_sfx_capture(); assert(audio.play_sfx("sfx_gavel_rap") and audio.debug_active_sfx_count() == 1); audio.end_cutscene_sfx_capture(true); assert(audio.debug_active_sfx_count() == 0)
	var transient: Variant = audio.play_transient_sfx("voice_001", 0.6); assert(transient is AudioStreamPlayer); audio.stop_transient_sfx(transient); assert(audio.debug_active_sfx_count() == 0)
	events.emit("quest:accepted", {"restored": true}); assert(audio.debug_active_sfx_count() == 0); events.emit("quest:accepted", {}); assert(audio.debug_active_sfx_count() == 1); audio.stop_all_playback(); assert(audio.get_current_bgm_id() == null and audio.get_active_ambient_ids().is_empty() and audio.debug_active_sfx_count() == 0)
	audio.apply_scene_audio(null, ["night_alley_wind"]); assert(audio.get_active_ambient_ids() == ["night_alley_wind"] and audio.get_requested_bgm_id() == null and audio.get_requested_ambient_ids() == ["night_alley_wind"]); audio.deserialize({"ambientVolume": 0.3}); assert(audio.get_active_ambient_ids() == ["night_alley_wind"] and audio.get_volume("ambient") == 0.3)
	audio.apply_scene_audio(null, ["amb_light_rain_loop", "amb_riverbank_loop"]); assert(audio.get_active_ambient_ids() == ["amb_light_rain_loop", "amb_riverbank_loop"])
	audio.destroy(); assert(events.listener_count() == 0); remove_child(audio); audio.free(); assets.clear_cache(); assets.dispose(); await get_tree().create_timer(0.5).timeout; print("AudioManager config/mix/scene/capture/system-SFX lifecycle test: PASS"); get_tree().quit(0)
