extends Node


func _ready() -> void:
	var repository := ProjectSettings.globalize_path("res://").trim_suffix("/").get_base_dir(); var assets := RuntimeAssetManager.new(RuntimeResourceLocator.new(RuntimeResourceLocator.DEVELOPMENT, repository)); var renderer := RuntimeRenderer.new(); add_child(renderer); renderer.init_renderer(); renderer.set_viewport_size(800, 600); var camera := RuntimeCamera.new(renderer.world_container); camera.set_screen_size(800, 600); var cut := RuntimeCutsceneRenderer.new(renderer, camera, assets); cut.set_time_scale(0.0); cut.set_resolve_display(func(text: String) -> String: return text.replace("{{x}}", "已解析"))
	await cut.fade_to_black(100); assert(cut.has_fade_overlay()); await cut.fade_from_black(100); cut.set_debug_world_fade_alpha(0.5); assert(is_equal_approx(cut.world_fade_overlay.color.a, 0.5)); await cut.fade_world_from_black(100); await cut.flash_white(100); await cut.wait_ms(100); await cut.show_title("标题 {{x}}", 100)
	var box := cut.show_dialogue_box("正文", "人物"); assert(box != null); cut.dismiss_dialogue_box(box); var subtitle := cut.show_subtitle("字幕", {"subtitleBand": "movieBottom", "subtitleAlign": "right"}); cut.dismiss_subtitle(subtitle)
	var image_a := "/resources/runtime/images/illustrations/李天狗神仙岭大战旱魃/01_mountain_path_to_shenxianling.png"; var image_b := "/resources/runtime/images/illustrations/ghost_bride_flashback.png"; assert(cut.show_img(image_a)); assert(cut.get_active_image_handles() == [RuntimeCutsceneRenderer.ANON_SHOT_ID]); assert(cut.show_img(image_b)); assert(cut.get_active_image_handles().size() == 1); assert(cut.show_img(image_a, "named", {"fromScale": 1.0, "toScale": 1.1, "durationMs": 10}, 5)); assert(cut.get_active_image_handles().size() == 2); cut.hide_img("named")
	assert(cut.show_anim_layer("/resources/runtime/animation/fx_teapot_steam/anim.json", "fx", {"xPercent": 50, "yPercent": 50, "widthPercent": 30, "alpha": 0.7, "zIndex": 60})); cut.update(0.1); assert(cut.get_active_image_handles().has("fx"))
	var parallax_raw: Variant = assets.load_json("/assets/data/parallax_scenes.json"); assert(parallax_raw is Array and cut.show_parallax_scene(parallax_raw[0], "para")); assert(cut.get_active_image_handles().has("para")); cut.show_movie_bar(0.12); assert(cut.has_movie_bars()); cut.hide_movie_bar(); assert(not cut.has_movie_bars()); await cut.camera_move(300, 250, 100); assert(camera.get_x() == 300 and camera.get_y() == 250); await cut.camera_zoom(1.5, 100); assert(camera.get_zoom() == 1.5); await cut.fade_to_black(100); await cut.fade_world_to_black(100); await cut.settle_fade_overlays_before_cleanup(500); assert(cut.fade_overlay.color.a == 0.0 and cut.world_fade_overlay.color.a == 0.0)
	cut.cleanup(); assert(cut.get_active_image_handles().is_empty() and not cut.has_movie_bars() and not cut.has_fade_overlay()); cut.destroy(); assets.dispose(); renderer.destroy_renderer(); remove_child(renderer); renderer.free(); print("CutsceneRenderer 16-present primitive contract test: PASS"); get_tree().quit(0)
