extends Node

var log: Array = []


func _ready() -> void:
	var repository := ProjectSettings.globalize_path("res://").trim_suffix("/").get_base_dir(); var assets := RuntimeAssetManager.new(RuntimeResourceLocator.new(RuntimeResourceLocator.DEVELOPMENT, repository)); var events := RuntimeEventBus.new(); var flags := RuntimeFlagStore.new(events); flags.configure_registry(assets.load_json("/assets/data/flag_registry.json")); var strings := RuntimeStringsProvider.new(); assert(strings.load(assets)); var input := RuntimeInputManager.new(); var state := RuntimeGameStateController.new(input, events); var actions := RuntimeActionExecutor.new(events, flags, state); var inventory := RuntimeInventoryManager.new(events, flags); inventory.init({"eventBus": events, "flagStore": flags, "strings": strings, "assetManager": assets}); assert(inventory.load_defs()); var rules := RuntimeRulesManager.new(events, flags); rules.init({"eventBus": events, "flagStore": flags, "strings": strings, "assetManager": assets}); assert(rules.load_defs()); var quests := RuntimeQuestManager.new(events, flags, actions); quests.init({"eventBus": events, "flagStore": flags, "strings": strings, "assetManager": assets}); assert(quests.load_defs()); var offers := RuntimeRuleOfferRegistry.new(); actions.register_inventory_rule_quest_handlers(inventory, rules, quests, offers, strings)
	var manager := RuntimeEncounterManager.new(events, flags, actions); manager.init({"strings": strings, "assetManager": assets}); assert(manager.load_defs() and manager.has_encounter("old_box_encounter") and manager.has_encounter("ghost_encounter") and not manager.has_encounter("missing")); manager.set_condition_eval_context_factory(func() -> Dictionary: return {"flagStore": flags, "questManager": quests}); manager.set_rule_name_resolver(func(id: String) -> Variant: return rules.get_rule_def(id)); manager.set_resolve_display(func(text: String) -> String: return text.replace("{{name}}", "已解算"))
	for name: String in ["encounter:start", "encounter:narrative", "encounter:options", "encounter:result", "encounter:end"]: events.on(name, func(payload: Variant) -> void: log.push_back({"event": name, "payload": payload.duplicate(true) if payload is Dictionary else payload}))
	assert(not manager.start_encounter("missing") and not manager.is_active()); assert(manager.start_encounter("old_box_encounter") and manager.is_active() and log[-1].event == "encounter:narrative"); manager.generate_options(); assert(manager.get_current_options().size() == 2 and manager.get_current_options()[0].enabled); assert(await manager.choose_option(0)); assert(flags.get_value("read_box_note") == true and log[-1].event == "encounter:result"); manager.end_encounter(); assert(not manager.is_active() and log[-1].event == "encounter:end")
	assert(manager.start_encounter("ghost_encounter")); manager.generate_options(); var options := manager.get_current_options(); assert(options.size() == 3 and options[1].type == "special" and options[1].enabled == false); flags.set_value("rule_rule_no_go_night_discovered", true); manager.generate_options(); options = manager.get_current_options(); assert(options.size() == 4 and options[1].type == "rule" and options[1].enabled == false); assert(inventory.add_item("taomu", 1)); manager.generate_options(); options = manager.get_current_options(); assert(options[2].type == "special" and options[2].enabled == true); manager.choose_option(2); manager.choose_option(2); await get_tree().process_frame; assert(inventory.get_item_count("taomu") == 0 and flags.get_value("ghost_used_taomu") == true and log[-1].event == "encounter:result"); manager.end_encounter()
	assert(manager.start_encounter("old_box_encounter") and manager.start_encounter("ghost_encounter") and manager.current_encounter.id == "ghost_encounter"); manager.end_encounter()
	manager.encounter_defs.synthetic_empty = {"id": "synthetic_empty", "narrative": "空", "options": [{"text": "隐藏", "type": "general", "conditions": [{"flag": "never_visible", "op": "==", "value": true}], "resultActions": []}]}; assert(manager.start_encounter("synthetic_empty")); manager.generate_options(); assert(not manager.is_active() and log[-1].event == "encounter:end")
	manager.destroy(); manager.free(); quests.destroy(); quests.free(); rules.destroy(); rules.free(); inventory.destroy(); inventory.free(); offers.destroy(); actions.destroy(); state.destroy(); input.destroy(); input.free(); flags.destroy(); events.clear(); assets.dispose(); print("EncounterManager two-def/options/consume/result contract test: PASS"); get_tree().quit(0)
